server:
  port: 8000


# localhost:8080/multiplications/~ 요청이 게이트웨이로 들어오게되면, predicates를 탐색하여,
# 해당 라우트에 해당하는 엔드포인트로 전달합니다.

# 7/30 (refactor) 아래와 같이 서비스 명으로 로드밸런싱 할 수 있음
# 각 서비스의 yml 설정에 등록을 해야함
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: multiplications
          uri: lb://MULTIPLICATION-SERVICE
          predicates:
            - Path=/api/multiplications/**
        - id: results
          uri: lb://RESULTS-SERVICE
          predicates:
            - Path=/api/results/**
        - id: leaders
          uri: lb://LEADER-SERVICE
          predicates:
            - Path=/api/leaders/**
        - id: stats
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/api/stats/**


    # 설정에서 리본 및 유레카 사용 설정을 비활성화합니다.
    loadbalancer:
      eureka:
        enabled: false


# 아래는 새로운 프로젝트에서의 서비스 레지스트리 설정임
#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#    eureka:
#      client:
#        serviceUrl:
#          defaultZone: http://localhost:8761/eureka/


management:
  endpoints:
    web:
      exposure:
        include: trace